---
- name: Install Deps
  become: yes
  ansible.builtin.apt:
    name:
      - jq
    state: present
    update_cache: yes
    cache_valid_time: 300
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Ensure bin directory exists
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: yes
  with_items:
    - "/home/{{ user }}/bin"

- name: Determine the latest chia-exporter release file
  uri:
    url: https://api.github.com/repos/Chia-Network/chia-exporter/releases/latest
    return_content: true
  register: json_response

- name: Get latest chia-exporter release
  become: yes
  get_url:
    url: "{{ json_reponse.json.assets.[?name=='chia-exporter-linux-arm64.zip'].browser_download_url }}"
    dest: "/home/{{ user }}/bin"
    mode: '0750'

- name: Chia Exporter Systemd Config
  become: yes
  ansible.builtin.template:
    src: "chia-exporter.service.j2"
    dest: "/etc/systemd/system/{{ chia_exporter_service_name }}"
    owner: root
    group: root
  notify: restart-chia-exporter

- name: Ensure chia-exporter service is in desired boot and current state
  become: yes
  ansible.builtin.systemd:
    name: "{{ chia_exporter_service_name }}"
    daemon_reload: yes
    enabled: "{{ chia_exporter_start_on_boot }}"
    state: "{{ chia_exporter_start_now | ternary('started','stopped') }}"
