---
- name: Load architecture specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_architecture}}.yml'
      paths:
        - 'vars'

- name: Ensure old installation methods are cleaned up
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    recurse: yes
  with_items:
    - "/home/{{ user }}/bin/chia-exporter"

- name: Chia Exporter Repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [arch={{ chia_exporter_repo_arch }} signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/chia-exporter/debian/ stable main
    update_cache: yes

- name: Install Chia Exporter
  become: yes
  ansible.builtin.apt:
    name:
      - "chia-exporter{{ ( chia_exporter_version == 'latest' ) | ternary('', '=' + chia_exporter_version) }}"
    update_cache: yes
    cache_valid_time: 300
    state: "{{ ( chia_exporter_version == 'latest' ) | ternary('latest', 'present') }}"
  notify: restart-chia-exporter
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Copy maxmind DB from S3
  become: yes
  become_user: "{{ user }}"
  shell: |
    aws --no-progress s3 cp "s3://{{ maxmind_db_backup_bucket }}/{{ maxmind_db_name }}" "/home/{{ user }}/bin/{{ maxmind_db_name }}"
  args:
    creates: "/home/{{ user }}/bin/{{ maxmind_db_name }}"
  notify: restart-chia-exporter
  when: download_maxmind_db

- name: Chia Exporter Systemd Config
  become: yes
  ansible.builtin.template:
    src: "chia-exporter.service.j2"
    dest: "/etc/systemd/system/{{ chia_exporter_service_name }}"
    owner: root
    group: root
  notify: restart-chia-exporter

- name: Ensure chia-exporter service is in desired boot and current state
  become: yes
  ansible.builtin.systemd:
    name: "{{ chia_exporter_service_name }}"
    daemon_reload: yes
    enabled: "{{ chia_exporter_start_on_boot }}"
    state: "{{ chia_exporter_start_now | ternary('started','stopped') }}"
