---
- name: Backup Config
  template:
    src: backup.sh.j2
    dest: "/home/{{ user }}/backup.sh"
    mode: '0755'

- name: Add cron to backup every 12 hours
  become: yes
  ansible.builtin.cron:
    name: "Blockchain Backup"
    user: "{{ user }}"
    minute: "{{ backup_cron_minute }}"
    hour: "{{ backup_cron_hour }}"
    job: "/home/{{ user }}/backup.sh > /home/{{ user }}/backup.log 2>&1"
