---
- name: Backup Config
  ansible.builtin.template:
    src: backup.sh.j2
    dest: "/home/{{ user }}/backup.sh"
    mode: '0755'

- name: Create log directory for backup script
  ansible.builtin.file:
    path: "/home/{{ user }}/backup-logs"
    state: directory
    mode: "0755"

- name: Add cron to do routine backups
  become: true
  ansible.builtin.cron:
    name: "Blockchain Backup"
    user: "{{ user }}"
    minute: "{{ backup_cron_minute }}"
    hour: "{{ backup_cron_hour }}"
    job: "/home/{{ user }}/backup.sh >> /home/{{ user }}/backup-logs/backup.log 2>&1"

- name: Add logrotate script for backup log file
  become: true
  ansible.builtin.template:
    src: backup-script-logrotate.j2
    dest: "/etc/logrotate.d/backup-script-logrotate"
    mode: '0644'
