---
- name: Install jq
  become: true
  ansible.builtin.apt:
    name:
      - jq
    state: present
    update_cache: true
    cache_valid_time: 300
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Backup Config
  template:
    src: backup.sh.j2
    dest: "/home/{{ user }}/backup-vault.sh"
    mode: '0755'

- name: Add cron to backup every 12 hours
  become: yes
  ansible.builtin.cron:
    name: "Vault Backup"
    user: "{{ user }}"
    minute: "30"
    hour: "8,20"
    job: "/home/{{ user }}/backup-vault.sh > /home/{{ user }}/backup-vault.log 2>&1"
