---
- name: Load architecture specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_architecture}}.yml'
      paths:
        - 'vars'
  tags: cadt

- name: Add CADT Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ cadt_repo_arch }} signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/cadt/debian/ stable main
    update_cache: true
  tags: cadt

- name: Install CADT
  become: true
  ansible.builtin.apt:
    name:
      - "cadt{{ (cadt_api_version == 'latest') | ternary('', '=' + cadt_api_version) }}"
    update_cache: true
    cache_valid_time: 300
    state: "{{ (cadt_api_version == 'latest') | ternary('latest', 'present') }}"
  register: cadt_install
  notify: restart-cadt
  retries: 100
  tags: cadt

- name: Ensure CADT is in desired boot and current state
  become: true
  ansible.builtin.systemd:
    name: "cadt@{{ user }}.service"
    daemon_reload: true
    enabled: true
    state: started
  tags: cadt

- name: Add CADT config file
  ansible.builtin.template:
    src: "config.yaml.j2"
    dest: "{{ chia_root }}/cadt/v1/config.yaml"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  notify:
    - restart-cadt
  tags: cadt

- name: Create Nginx proxy for CADT
  become: true
  ansible.builtin.template:
    src: cadt.conf.j2
    dest: /etc/nginx/conf.d/{{ cadt_api_hosts | first }}.conf
    owner: root
    group: root
    mode: '0644'
  when: cadt_api_proxy == true and ((cadt_api_hosts | difference(cadt_ui_hosts)) | length>0)
  tags: cadt
  notify: Reload-nginx

- name: Create directory for CADT API include
  become: true
  ansible.builtin.file:
    path: /etc/nginx/cadt_proxy_includes
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
  when:
    - cadt_api_proxy == true
  tags: cadt

- name: Template Nginx config for CADT API proxy
  become: true
  ansible.builtin.template:
    src: cadt-proxy.inc.j2
    dest: /etc/nginx/cadt_proxy_includes/cadt-api-proxy-{{ cadt_port }}.inc
    owner: root
    group: root
    mode: '0644'
  when:
    - cadt_api_proxy == true
  tags: cadt
  notify: Reload-nginx

# If CADT domains are the same as the CADT-UI domains, use the existing CADT-UI Nginx file
- name: Add CADT proxy include into existing CADT-UI Nginx config (if hosted on the same domain)
  become: true
  ansible.builtin.lineinfile:
    path: /etc/nginx/conf.d/{{ cadt_ui_hosts | first }}.conf
    state: present
    insertafter: '    index index.html;'
    line: "    include /etc/nginx/cadt_proxy_includes/*.inc;"
  when: ((cadt_api_hosts | difference(cadt_ui_hosts)) | length==0) and ((cadt_ui_hosts | difference(cadt_api_hosts)) | length==0)
  tags: cadt
  notify: Reload-nginx

- name: Add custom monit config to conf.d for CADT
  become: true
  ansible.builtin.template:
    src: monit_config.j2
    dest: /etc/monit/conf.d/cadt_monit_{{ user }}
    owner: root
    group: root
    mode: '0644'
  notify: restart-monit
  tags: cadt

- name: Make backup directory
  ansible.builtin.file:
    path: "{{ backup_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  tags: cadt

- name: Copy backup script
  become: true
  ansible.builtin.template:
    src: backups.sh.j2
    dest: /home/{{ user }}/backups.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
  tags: cadt

- name: Create cron job for backups
  ansible.builtin.cron:
    name: "CADT backups"
    minute: "51"
    hour: "1"
    job: "bash /home/{{ user }}/backups.sh > /home/{{ user }}/backup.log 2>&1"
    user: "{{ user }}"
  tags: cadt
