- name: Chia Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ chia_repo_arch }} signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/debian/ stable main
    update_cache: true

- name: Install Chia
  become: true
  ansible.builtin.apt:
    name:
      - "{{ chia_apt_package }}{{ (repo_ref == 'latest') | ternary('', '=' + repo_ref) }}"
    update_cache: true
    cache_valid_time: 300
    state: "{{ (repo_ref == 'latest') | ternary('latest', 'present') }}"
  register: chia_install
  notify: restart-chia
  retries: 100
  until: chia_install is success or ('Failed to lock apt for exclusive operation' not in chia_install.msg and '/var/lib/dpkg/lock' not in chia_install.msg)

- name: Chia Init
  become: true
  become_user: "{{ user }}"
  ansible.builtin.shell: |
    chia init --fix-ssl-permissions
  environment:
    CHIA_ROOT: "{{ chia_root }}"
  when: chia_install.changed or chia_force_init
