- name: Ensure the per-instance directory exists
  become: true
  ansible.builtin.file:
    path: /var/lib/cloud/scripts/per-instance/
    state: directory
    owner: root
    group: root
    recurse: true

- name: Chia Cert Script
  become: true
  ansible.builtin.template:
    src: "cloudinit/chia-certs.sh"
    dest: "/var/lib/cloud/scripts/per-instance/chia-certs.sh"
    owner: root
    group: root
    mode: "0755"
