---
- name: Create directory for CA files
  become: yes
  ansible.builtin.file:
    path: "/home/{{ user }}/chia-ca"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: yes
  when:
    - chia_ca_crt != ""
    - chia_ca_key != ""
    - chia_private_ca_crt != ""
    - chia_private_ca_key != ""

- name: Write CA files
  become: yes
  no_log: yes # Don't expose secrets in logs
  copy:
    content: "{{ item.content }}"
    dest: /home/{{ user }}/chia-ca/{{ item.filename }}
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items:
    - content: "{{ chia_ca_crt }}"
      filename: "chia_ca.crt"
    - content: "{{ chia_ca_key }}"
      filename: "chia_ca.key"
    - content: "{{ chia_private_ca_crt }}"
      filename: "private_ca.crt"
    - content: "{{ chia_private_ca_key }}"
      filename: "private_ca.key"
  register: ca_content
  when:
    - chia_ca_crt != ""
    - chia_ca_key != ""
    - chia_private_ca_crt != ""
    - chia_private_ca_key != ""

- name: Run init with custom CA
  become: yes
  become_user: "{{ user }}"
  shell: |
    chia init -c /home/{{ user }}/chia-ca
  environment:
    PATH: "/home/{{ user }}/chia-blockchain/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    CHIA_ROOT: "{{ chia_root }}"
  when: ca_content.changed
  notify: restart-chia
