- name: HW VDF Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ chia_repo_arch }} signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/chiavdf-hw/debian/ stable main
    update_cache: true

- name: Install HW VDF Client
  become: true
  ansible.builtin.apt:
    name:
      - "chiavdf-hw{{ (chia_hw_vdf_version == 'latest') | ternary('', '=' + chia_hw_vdf_version) }}"
    update_cache: true
    cache_valid_time: 300
    state: "{{ (chia_hw_vdf_version == 'latest') | ternary('latest', 'present') }}"
    allow_downgrade: true
  register: hwvdf_install
  notify: restart-chia
  retries: 100
  until: hwvdf_install is success or ('Failed to lock apt for exclusive operation' not in hwvdf_install.msg and '/var/lib/dpkg/lock' not in hwvdf_install.msg)

- name: Add custom monit hw-vdf config to conf.d
  become: true
  ansible.builtin.template:
    src: monit_hw_vdf.j2
    dest: /etc/monit/conf.d/chia_hw_vdf
    mode: "0644"
  when: chia_add_hw_vdf_monit_config
  notify: restart-monit

- name: Add a notify script that send a webhook to Keybase if monit restarts the chia service
  become: true
  ansible.builtin.template:
    src: monit_restart_hw_vdf_with_alert.sh.j2
    dest: /etc/monit/monit-notify-hw-vdf.sh
    mode: "0744"
  when: chia_add_hw_vdf_monit_config
  notify: restart-monit
