---
- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name:
      - nginx
    state: present
    update_cache: true
    cache_valid_time: 300
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Ensure service is in desired boot and current state
  become: true
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: true
    enabled: "{{ nginx_start_on_boot }}"
    state: "{{ nginx_start_now | ternary('started', 'stopped') }}"

- name: Ensure we have the latest nginx options from certbot
  become: true
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
    dest: /etc/nginx/snippets/options-ssl-nginx.conf
    mode: '0440'
  notify: Reload-nginx
