---
- name: Install smartmontools
  package:
    name: smartmontools
    state: present
  become: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /opt/smartctl_exporter
    - /var/lib/smartctl_exporter
  become: true

- name: Download smartctl_exporter
  get_url:
    url: "https://github.com/prometheus-community/smartctl_exporter/releases/download/v{{ smartctl_exporter_version }}/smartctl_exporter-{{ smartctl_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/smartctl_exporter.tar.gz
    mode: '0644'
  become: true

- name: Extract smartctl_exporter
  unarchive:
    src: /tmp/smartctl_exporter.tar.gz
    dest: /opt/smartctl_exporter
    remote_src: yes
    owner: root
    group: root
    extra_opts: [--strip-components=1]
  become: true

- name: Install systemd service
  template:
    src: smartctl_exporter.service.j2
    dest: /etc/systemd/system/smartctl_exporter.service
    mode: '0644'
  become: true
  notify: restart smartctl_exporter

- name: Start and enable smartctl_exporter service
  systemd:
    name: smartctl_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  become: true
