---
- name: Copy over the db-pull.sh file
  template:
    src: "db-pull.sh.j2"
    dest: "{{ chia_root }}/db-pull.sh"

- name: Install the DB unit file
  template:
    src: "db-pull.service"
    dest: "/etc/systemd/system/db-pull.service"
    owner: root
    group: root
    mode: 0755

- name: Enable DB pull service
  systemd:
    name: db-pull.service
    daemon_reload: true
    state: stopped
    enabled: yes
