---
# Use ephemeral AWS credentials provided in the CI/CD actions. Make sure the
# following variables are set:
#   tmp_aws_access_key
#   tmp_aws_secret_key
#   tmp_aws_session_token
#   sentinelone_debian_installer
- name: Download SentinelOne installer from private S3 bucket
  ansible.builtin.shell: "aws --no-progress s3 cp s3://{{ sentinelone_bucket }}/sentinelone/SentinelAgent_linux_v22_1_1_4.deb /tmp/SentinelAgent_linux_v22_1_1_4.deb"
  args:
    creates: /tmp/SentinelAgent_linux_v22_1_1_4.deb
  become: yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Transfer SentinelOne configuration file that will be used during installation only
  ansible.builtin.template:
    src: s1-config.cfg
    dest: /tmp/s1-config.cfg
    owner: root
    group: root
    mode: '0700'
  become: yes

- name: Install SentinelOne package
  ansible.builtin.apt:
    deb: /tmp/SentinelAgent_linux_v22_1_1_4.deb
    state: present
  become: yes
  environment:
    S1_AGENT_INSTALL_CONFIG_PATH: "/tmp/s1-config.cfg"
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

# Don't leave the sensitive config file on the system after install
- name: Remove SentinelOne installation configuration file
  ansible.builtin.file:
    path: /tmp/s1-config.cfg
    state: absent
  become: yes

- name: Start SentinelOne agent
  ansible.builtin.command: "/opt/sentinelone/bin/sentinelctl control start"
  become: yes

