- name: restart-chia-exporter
  become: true
  ansible.builtin.service:
    name: "{{ chia_exporter_service_name }}"
    state: restarted
  when: chia_exporter_start_now
  register: systemd_action
  retries: 10
  until: systemd_action is success

- name: restart-monit
  become: true
  ansible.builtin.service:
    name: monit
    state: restarted
  when: chia_exporter_add_monit_config and monit_start_now
  register: systemd_action
  retries: 10
  until: systemd_action is success
