---
- name: Create directory for Core Registry UI files
  become: true
  ansible.builtin.file:
    path: /var/www/{{ core_registry_ui_hosts | first }}
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: core_registry_ui_hosting == "local"
  tags: core-registry-ui

# Create this directory to be used for the Core Registry API proxy files.  If core registry isn't
# proxying, this directory is empty and won't do anything.  The core-registry-api ansible role
# will manage adding files to this directory and reloading Nginx.
- name: Create directory for Core Registry API include
  become: true
  ansible.builtin.file:
    path: /etc/nginx/{{ core_registry_api_hosts | first }}_proxy_includes
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
  when:
    - core_registry_api_proxy == true
  tags: core-registry-ui

- name: Copy and uncompress Core Registry UI files
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/Chia-Network/core-registry-ui/releases/{{ (core_registry_ui_version == 'latest') | ternary('latest/download', 'download/' +  core_registry_ui_version )}}/core-registry-ui-web-build.tar.gz
    dest: /var/www/{{ core_registry_ui_hosts | first }}
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
  when: core_registry_ui_hosting == "local"
  tags: core-registry-ui

- name: Install htpasswd prerequisites for ansible
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-passlib
    state: present
    update_cache: true
    cache_valid_time: 300
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
  when: basic_authentication
  tags: core-registry-ui

- name: Create htpasswd file for basic authentication
  become: true
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ basic_authentication_user }}"
    password: "{{ basic_authentication_password }}"
    owner: root
    group: www-data
    mode: '0640'
  when: basic_authentication
  tags: core-registry-ui

- name: Template Nginx config for Core Registry
  become: true
  ansible.builtin.template:
    src: cadt-ui.local.conf.j2
    dest: /etc/nginx/conf.d/{{ core_registry_ui_hosts | first }}.conf
    owner: root
    group: root
    mode: '0644'
  when: core_registry_ui_hosting == "local"
  tags: core-registry-ui
  notify: Reload-nginx
