---
- name: Create directory for Core Registry UI files
  become: true
  ansible.builtin.file:
    path: /var/www/{{ climate_apps_domains | first }}/core-registry-ui
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: core_registry_ui_hosting == "local"
  tags: core-registry-ui

- name: Copy and uncompress Core Registry UI files
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/Chia-Network/core-registry-ui/releases/{{ (core_registry_ui_version == 'latest') | ternary('latest/download', 'download/' +  core_registry_ui_version )}}/core-registry-ui-web-build.tar.gz
    dest: /var/www/{{ climate_apps_domains | first }}/core-registry-ui
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
  when: core_registry_ui_hosting == "local"
  tags: core-registry-ui

- name: Template Nginx config for Core Registry
  become: true
  ansible.builtin.template:
    src: core_registry_ui.inc.j2
    dest: /etc/nginx/{{ climate_apps_domains | first }}_ui_includes/core_registry_ui.inc
    owner: root
    group: root
    mode: '0644'
  when: core_registry_ui_hosting == "local"
  tags: core-registry-ui
  notify: Reload-nginx

- name: Upload Core Registry UI config for auto connect to API
  become: true
  ansible.builtin.template:
    src: config.json.j2
    dest: /var/www/{{ climate_apps_domains | first }}/core-registry-ui/build/config.json
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: core_registry_ui_hosting == "local" and core_registry_cadt_api_url != "" and core_registry_tokenization_api_url != "" and core_registry_explorer_api_url != ""
  tags: core-registry-ui

- name: Upload Core Registry UI config for custom colors
  become: true
  ansible.builtin.template:
    src: colors.json.j2
    dest: /var/www/{{ climate_apps_domains | first }}/core-registry-ui/build/colors.json
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: core_registry_ui_hosting == "local" and core_registry_ui_custom_colors == "true"
  tags: core-registry-ui
