---
- name: get userify shim
  get_url:
    url: https://shim.userify.com/installer.sh
    dest: /tmp
    mode: 0777
  notify: start_userify

- name: install userify
  shell: './installer.sh'
  args:
    chdir: /tmp
    creates: /opt/userify
  environment:
    api_id: "{{userify_api_id}}"
    api_key: "{{userify_api_key}}"
  notify:
    - start_userify
    - start_userify_timer

- name: wrap shim with systemd
  copy:
    src: "files/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: 0755
  notify:
    - start_userify
    - start_userify_timer
  with_items:
    - userify.service
    - userify.timer

- name: Template userify creds config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  notify:
    - start_userify
    - start_userify_timer
  with_items:
    - src: creds.py
      dest: /opt/userify/creds.py
    - src: userify_config.py
      dest: /opt/userify/userify_config.py
