[sources.chia]
type = "file"
ignore_older_secs = 600
include = ["{{ chia_root }}/log/debug.log"]
read_from = "beginning"

[sinks.loki]
type = "loki"
inputs = ["chia"]
endpoint = "{{ loki_endpoint }}"
encoding.codec = "json"
healthcheck.enabled = true
labels.application = "{{ application }}"
labels.component = "{{ component }}"
labels.network = "{{ network }}"
labels.group = "{{ group_tag }}"
labels.ref = "{{ repo_ref }}"
labels.host = "{% raw %}{{ host }}{% endraw %}"

{% if loki_basic_auth %}
auth.strategy = "basic"
auth.user = "{{ loki_basic_auth_username }}"
auth.password = "{{ loki_basic_auth_password }}"
{% endif %}
