---
- name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: Get docker key
  become: yes
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Get Docker Repo
  become: yes
  shell: |
    echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  register: docker
  when: "ansible_architecture == 'aarch64'"



- name: Get Docker Repo
  become: yes
  shell: |
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  register: docker
  when: "ansible_architecture == 'x86_64'"
- debug:
    msg: "{{ docker.stdout }}"

#- name: Docker repository
#  become: yes
#  ansible.builtin.apt_repository:
#    repo:  deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
#  when: "ansible_architecture == 'x86_64'"

#- name: Docker repository
#  become: yes
#  ansible.builtin.apt_repository:
#    repo: deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
#  when: "ansible_architecture == 'arm64'"

- name: Update apt packages
  become: yes
  shell: apt-get update

- name: Install Docker
  become: yes
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
