---
- name: Upload binary
  become: yes
  ansible.builtin.copy:
    src: "{{ local_bin_path }}"
    dest: "/usr/local/bin/{{ bin_name }}"
    mode: '0755'
  notify: restart-blockchain-status

- name: Systemd Config
  become: yes
  ansible.builtin.template:
    src: "systemd-template.service"
    dest: "/etc/systemd/system/{{ bin_name }}.service"
    owner: root
    group: root
  notify: restart-blockchain-status

- name: Blockchain status config
  template:
    src: "blockchain-status.yaml.j2"
    dest: "/home/{{ user }}/.blockchain-status.yaml"
  notify: restart-blockchain-status

- name: Ensure service starts on boot and is started now (if set)
  become: yes
  ansible.builtin.systemd:
    name: "{{ bin_name }}"
    daemon_reload: yes
    enabled: "{{ start_on_boot }}"
    state: "{{ start_now | ternary('started','stopped') }}"
