---
- include_role: geerlingguy.mac.homebrew

- name: Install Prometheus Node Exporter
  become: no
  homebrew:
    name: node_exporter
    state: present

- name: Ensure service is in desired boot and current state
  become: no
  shell: brew services start node_exporter
