---
- name: Install Prometheus Node Exporter
  become: no
  homebrew:
    name: node-exporter
    state: present

- name: Ensure service is in desired boot and current state
  become: yes
  shell: brew services start node_exporter
