---
- name: Install Prometheus Node Exporter
  become: yes
  homebrew:
    name: node-exporter
    state: present
  retries: 100
  until: result is successful

- name: Ensure service is in desired boot and current state
  become: yes
  shell: brew services start node_exporter
