---
- name: Install Prometheus Node Exporter
  become: true
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
    state: present
    update_cache: true
    cache_valid_time: 300
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Ensure service is in desired boot and current state
  become: true
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    daemon_reload: true
    enabled: "{{ prometheus_start_on_boot }}"
    state: "{{ prometheus_start_now | ternary('started', 'stopped') }}"
