---
- name: Install Prometheus Node Exporter
  become: yes
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
    state: present

- name: Ensure service is in desired boot and current state
  become: yes
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    daemon_reload: yes
    enabled: "{{ start_on_boot }}"
    state: "{{ start_now | ternary('started','stopped') }}"
