---
#This workflow is constructed to support multiple OSs
- name: Install from node-exporter on Debian-based OSs
  ansible.builtin.include_tasks: "debian.yml"
  when: ansible_os_family == "Debian"

- name: Install from node-exporter on Darwin-based OSs
  ansible.builtin.include_tasks: "Darwin.yml"
  when: ansible_os_family == "Darwin"
