---
- name: Load architecture specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_architecture}}.yml'
      paths:
        - 'vars'
  tags: climate-explorer

- name: Add Climate Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ climate_explorer_repo_arch }} signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/climate-tokenization/debian/ stable main
    update_cache: true
  tags: climate-explorer

- name: Add Climate Pre-Release Repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch={{ climate_explorer_repo_arch }} signed-by=/usr/share/keyrings/chia.gpg] https://repo.chia.net/climate-tokenization-test/debian/ stable main
    update_cache: true
  when: climate_apt_prerelease
  tags: climate-explorer

- name: Install Climate Explorer
  become: true
  ansible.builtin.apt:
    name:
      - "climate-explorer-chia{{ (climate_explorer_api_version == 'latest') | ternary('', '=' + climate_explorer_api_version) }}"
    update_cache: true
    cache_valid_time: 300
    state: "{{ (climate_explorer_api_version == 'latest') | ternary('latest', 'present') }}"
    allow_downgrade: true
  register: climate_explorer_install
  notify: restart-climate-explorer
  retries: 100
  tags: climate-explorer

- name: Ensure Climate Explorer is in desired boot and current state
  become: true
  ansible.builtin.systemd:
    name: "climate-explorer-chia@{{ user }}.service"
    daemon_reload: true
    enabled: true
    state: restarted
  tags: climate-explorer

- name: Wait for Climate Explorer config file to be present before continuing
  ansible.builtin.wait_for:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    timeout: 20

- name: Edit bind address in existing climate token driver config file
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'CLIMATE_EXPLORER_SERVER_HOST: \d+\.\d+\.\d+\.\d+'
    replace: "CLIMATE_EXPLORER_SERVER_HOST: {{ climate_explorer_bind_address }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Edit BLOCK_START host in existing climate token driver config file
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'BLOCK_START: .*'
    replace: "BLOCK_START: {{ climate_explorer_block_start }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Edit CADT API host in existing climate token driver config file
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'CADT_API_SERVER_HOST: .*'
    replace: "CADT_API_SERVER_HOST: {{ climate_explorer_cadt_api_server_host }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Edit CADT API host in existing climate token driver config file
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'CADT_API_KEY.*'
    replace: "CADT_API_KEY: {{ climate_explorer_cadt_api_key }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Edit Chia full node rpc port in existing climate token driver config file
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'CHIA_FULL_NODE_RPC_PORT: \d+'
    replace: "CHIA_FULL_NODE_RPC_PORT: {{ chia_full_node_rpc_port }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Edit Chia wallet rpc port in existing climate token driver config file
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'CHIA_WALLET_RPC_PORT: \d+'
    replace: "CHIA_WALLET_RPC_PORT: {{ chia_wallet_rpc_port }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Configure port climate explorer listens on
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'CLIMATE_EXPLORER_PORT: \d+'
    replace: "CLIMATE_EXPLORER_PORT: {{ climate_explorer_port }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Set organization scanning flag in existing climate token driver config file
  become: true
  ansible.builtin.replace:
    path: "{{ chia_root }}/climate_token/config/config.yaml"
    regexp: 'SCAN_ALL_ORGANIZATIONS: .*'
    replace: "SCAN_ALL_ORGANIZATIONS: {{ climate_explorer_scan_all_organizations }}"
  tags: climate-explorer
  notify: restart-climate-explorer

- name: Template Nginx config for Climate Explorer API proxy
  become: true
  ansible.builtin.template:
    src: climate-explorer-proxy.inc.j2
    dest: /etc/nginx/{{ climate_apps_domains | first }}_proxy_includes/climate-explorer-api-proxy-{{ climate_explorer_port }}.inc
    owner: root
    group: root
    mode: '0644'
  when:
    - climate_explorer_api_proxy == true
  tags: climate-explorer
  notify: Reload-nginx

- name: Add custom monit config to conf.d for Climate Explorer
  become: true
  ansible.builtin.template:
    src: monit_config.j2
    dest: /etc/monit/conf.d/climate_explorer_monit_{{ user }}
    owner: root
    group: root
    mode: '0644'
  notify: restart-monit
  tags: climate-explorer

- name: Always restart Climate Explorer to ensure latest config changes are captured
  become: true
  ansible.builtin.systemd:
    name: "climate-explorer-chia@{{ user }}.service"
    daemon_reload: true
    enabled: true
    state: restarted
  tags: climate-explorer
