---
# AWS can't do UDP healthchecks, so this app checks for the DNS server to be ready for the healthcheck
- name: healthcheck binary
  become: yes
  ansible.builtin.copy:
    src: "./app/healthcheck"
    dest: /usr/local/bin/healthcheck
    mode: '0755'
  notify: restart-dns-healthcheck

- name: Healthcheck Systemd Config
  become: yes
  ansible.builtin.template:
    src: "dns-healthcheck.service"
    dest: "/etc/systemd/system/dns-healthcheck.service"
    owner: root
    group: root
  notify: restart-dns-healthcheck

- name: Ensure services start on boot and are started now
  become: yes
  ansible.builtin.systemd:
    name: dns-healthcheck
    daemon_reload: yes
    enabled: yes
    state: started
