---
- name: Get timelord-alert artifact
  become: yes
  shell: |
    aws s3 cp s3://{{timelord_bucket_path}} {{ install_path }}
    chown ubuntu:ubuntu {{ install_path }}/timelord-alerts
    chmod 755 {{ install_path }}/timelord-alerts
  notify: start-timelord-alerts

- name: Install the timelord-alerts unit file
  become: yes
  template:
    src: "timelord-alerts.service"
    dest: "/etc/systemd/system/timelord-alerts.service"
    owner: root
    group: root
    mode: 0755
  notify: start-timelord-alerts
