---
- name: Install Vault
  ansible.builtin.apt:
    name: vault={{ vault_version }}
    update_cache: yes
    state: present
  notify: restart-vault
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Template vault config
  ansible.builtin.template:
    src: vault.hcl
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
  notify: restart-vault

- name: Set to start on boot
  ansible.builtin.systemd:
    name: vault
    enabled: "{{ vault_start_on_boot }}"
    state: "{{ vault_start_now | ternary('started','stopped') }}"
