---
- name: Set a hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: hostname

- name: Update hostname in /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: 127.0.1.1 {{ hostname }}
    owner: root
    group: root
    mode: '0644'
  when: hostname
