---
- name: restart alloy
  become: true
  ansible.builtin.systemd:
    name: alloy
    state: restarted
    daemon_reload: true
  when: alloy_start_now
  register: systemd_action
  retries: 10
  until: systemd_action is success
