---
- debug:
    msg: "{{ ansible_architecture }}"

- name: Load architecture specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_architecture}}.yml'
      paths:
        - 'vars'

- name: Add runner_user to the docker group
  become: yes
  user:
    name: "{{ runner_user }}"
    groups: docker
    append: yes

- name: Make action-runner directory
  ansible.builtin.file:
    path: "{{ runner_directory_path }}"
    state: directory
    mode: '0755'

- name: Download runner tarball
  get_url:
    url: https://github.com/actions/runner/releases/download/v{{ runner_release_version }}/actions-runner-linux-{{ runner_download_arch }}-{{ runner_release_version }}.tar.gz
    dest: "{{ runner_directory_path }}"
    mode: '0755'

- name: Unarchive runner tarball
  ansible.builtin.unarchive:
    src: "{{ runner_directory_path }}/actions-runner-linux-{{ runner_download_arch }}-{{ runner_release_version }}.tar.gz"
    dest: "{{ runner_directory_path }}"
    remote_src: yes
    list_files: yes
    creates: "{{ runner_directory_path }}/svc.sh"

- name: Ensure actions-runner directory has correct permissions
  become: yes
  ansible.builtin.file:
    path: "{{ runner_directory_path }}"
    state: directory
    mode: '0755'
    owner: "{{ runner_user }}"
    group: "{{ runner_group }}"
    recurse: yes

- name: Configure the runner for GitHub
  become: yes
  become_user: "{{ runner_user }}"
  shell: ./config.sh --url https://github.com/Chia-Network --token "{{ runner_registration_token }}" --runnergroup "{{ runner_github_group }}" --labels "{{ runner_tags }}" --name "{{ inventory_hostname }}" --unattended
  args:
    chdir: "{{ runner_directory_path }}"
    creates: "{{ runner_directory_path }}/.runner"
  register: configure

- debug:
    msg: "{{ configure.stdout }}"

# The runner service becomes enabled in systemd after install
- name: Install the runner service
  shell: |
    sudo ./svc.sh install {{ runner_user }}
  args:
    chdir: "{{ runner_directory_path }}"
    creates: "/etc/systemd/system/actions.runner.Chia-Network.{{ inventory_hostname }}.service"
  register: install

- debug:
    msg: "{{ install.stdout }}"

- name: Ensure the service is in desired boot and current state
  become: true
  ansible.builtin.systemd:
    name: "actions.runner.Chia-Network.{{ inventory_hostname }}.service"
    daemon_reload: true
    enabled: "true"
    state: "started"
  register: systemd_action
  retries: 10
  until: systemd_action is success
