---
- debug:
    msg: "{{ ansible_architecture }}"

- name: Load architecture specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_architecture}}.yml'
      paths:
        - 'vars'

- name: Make action-runner directory
  ansible.builtin.file:
    path: "{{ path_to_runner_directory }}"
    state: directory
    mode: '0755'

- name: Download runner tarball
  get_url:
    url: https://github.com/actions/runner/releases/download/v{{runner_release_version}}/actions-runner-linux-{{download_arch}}-{{runner_release_version}}.tar.gz
    dest: "{{ path_to_runner_directory }}"
    mode: '0755'

- name: Unarchive runner tarball
  ansible.builtin.unarchive:
    src: "{{ path_to_runner_directory }}/actions-runner-linux-{{download_arch}}-{{runner_release_version}}.tar.gz"
    dest: "{{ path_to_runner_directory }}"
    remote_src: yes
    list_files: yes
    creates: "{{ path_to_runner_directory }}/svc.sh"

- name: Configure the runner for GitHub
  become: yes
  become_user: "{{ user }}"
  shell: ./config.sh --url https://github.com/Chia-Network --token "{{registration_token}}" --runnergroup "{{runner_group}}" --labels "{{runner_tags}}" --name "{{ ansible_hostname }}" --unattended
  args:
    chdir: "{{ path_to_runner_directory }}"
  register: configure

- debug:
    msg: "{{ configure.stdout }}"

# The runner service becomes enabled in systemd after install
- name: Install the runner service
  shell: |
    sudo ./svc.sh install
  args:
    chdir: "{{ path_to_runner_directory }}"
    creates: "/etc/systemd/system/actions.runner.Chia-Network.{{ ansible_hostname }}.service"
  register: install

- debug:
    msg: "{{ install.stdout }}"

- name:  Start the runner service
  shell: |
    sudo ./svc.sh start
    sudo ./svc.sh status
  args:
    chdir: "{{ path_to_runner_directory }}"
  register: output

- debug:
    msg: "{{ output.stdout }}"

- name: Add ansible_user to the docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
