- name: Restart-nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_start_now

- name: Reload-nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: nginx_start_now
