- name: restart-monit
  become: yes
  ansible.builtin.service:
    name: monit
    state: restarted
  when: monit_start_now
  register: systemd_action
  retries: 10
  until: systemd_action is success
