---
- name: Create directory for CADT UI files
  become: true
  ansible.builtin.file:
    path: /var/www/{{ cadt_ui_host }}
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: cadt_ui_hosting == "local"
  tags: cadt-ui

- name: Copy and uncompress CADT UI files
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/Chia-Network/cadt-ui/releases/download/{{ cadt_ui_version }}/cadt-ui-web-build.tar.gz
    dest: /var/www/{{ cadt_ui_host }}
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
  when: cadt_ui_hosting == "local"
  tags: cadt-ui

- name: Install htpasswd prerequisites for ansible
  become: true
  ansible.builtin.apt:
    pkg:
      - python3-passlib
    state: present
    update_cache: true
    cache_valid_time: 300
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
  when: basic_authentication
  tags: cadt-ui

- name: Create htpasswd file for basic authentication
  become: true
  community.general.htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ basic_authentication_user }}"
    password: "{{ basic_authentication_password }}"
    owner: root
    group: www-data
    mode: '0640'
  when: basic_authentication
  tags: cadt-ui

- name: Template Nginx config for CADT
  become: true
  ansible.builtin.template:
    src: cadt.local.conf.j2
    dest: /etc/nginx/conf.d/cadt.conf
    owner: root
    group: root
    mode: '0644'
  when: cadt_ui_hosting == "local"
  tags: cadt-ui
  notify: Reload-nginx

- name: Create directory for CADT API include
  become: true
  ansible.builtin.file:
    path: /etc/nginx/cadt_includes
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
  when:
    - cadt_ui_hosting == "local"
    - cadt_api_proxy == true
  tags: cadt-ui

- name: Template Nginx config for CADT API proxy
  become: true
  ansible.builtin.template:
    src: cadt-proxy.inc.j2
    dest: /etc/nginx/cadt_includes/cadt-api-proxy-{{ cadt_port }}.inc
    owner: root
    group: root
    mode: '0644'
  when:
    - cadt_ui_hosting == "local"
    - cadt_api_proxy == true
  tags: cadt-ui
  notify: Reload-nginx
