---
- name: Create directory for CADT UI files
  become: true
  ansible.builtin.file:
    path: /var/www/{{ climate_apps_domains | first }}/cadt-ui
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: cadt_ui_hosting == "local"
  tags: cadt-ui

- name: Copy and uncompress CADT UI files from Github
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/Chia-Network/cadt-ui/releases/{{ (cadt_api_version == 'latest') | ternary('latest/download', 'download/' +  cadt_ui_version )}}/cadt-ui-web-build.tar.gz
    dest: /var/www/{{ climate_apps_domains | first }}/cadt-ui
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
  when: cadt_ui_hosting == "local" and cadt_ui_use_custom_build == false
  tags: cadt-ui

- name: Upload custom CADT UI web build
  become: true
  ansible.builtin.copy:
    src: cadt-ui-web-build.tar.gz
    dest: /tmp/cadt-ui-web-build.tar.gz
    owner: "{{ user }}"
    group: "{{ user }}"
  when: cadt_ui_hosting == "local" and cadt_ui_use_custom_build == true
  tags: cadt-ui

- name: Uncompress custom CADT UI tar.gz
  become: true
  ansible.builtin.unarchive:
    src: /tmp/cadt-ui-web-build.tar.gz
    dest: /var/www/{{ climate_apps_domains | first }}/cadt-ui
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
  when: cadt_ui_hosting == "local" and cadt_ui_use_custom_build == true
  tags: cadt-ui

- name: Template Nginx config for CADT
  become: true
  ansible.builtin.template:
    src: cadt-ui.inc.j2
    dest: /etc/nginx/{{ climate_apps_domains | first }}_ui_includes/cadt_ui.inc
    owner: root
    group: root
    mode: '0644'
  when: cadt_ui_hosting == "local"
  tags: cadt-ui
  notify: Reload-nginx

- name: Upload CADT-UI config for auto connect to API
  become: true
  ansible.builtin.template:
    src: config.json.j2
    dest: /var/www/{{ climate_apps_domains | first }}/cadt-ui/build/config.json
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: cadt_ui_hosting == "local" and cadt_api_url != ""
  tags: cadt-ui

- name: Upload CADT-UI config for custom colors
  become: true
  ansible.builtin.template:
    src: colors.json.j2
    dest: /var/www/{{ climate_apps_domains | first }}/cadt-ui/build/colors.json
    mode: '0644'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: cadt_ui_hosting == "local" and cadt_ui_custom_colors == "true"
  tags: cadt-ui
