---
- name: Create directory for CADT UI files
  become: true
  ansible.builtin.file:
    path: /var/www/{{ cadt_ui_host }}
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"
  when: cadt_ui_hosting == "local"
  tags: cadt-ui

- name: Copy and uncompress CADT files
  become: true
  ansible.builtin.unarchive:
    src: https://github.com/Chia-Network/climate-warehouse-ui/releases/download/{{ cadt_ui_version }}/web-build.tar.gz
    dest: /var/www/{{ cadt_ui_host }}
    owner: "{{ user }}"
    group: "{{ user }}"
    remote_src: true
  when: cadt_ui_hosting == "local"
  tags: cadt-ui

- name: Template Nginx config for CADT
  become: true
  ansible.builtin.template:
    src: cadt.local.conf.j2
    dest: /etc/nginx/sites-available/cadt.conf
    owner: root
    group: root
    mode: '0644'
  when: cadt_ui_hosting == "local"
  tags: cadt-ui
  notify: Reload-nginx

- name: Symlink CADT config to make active
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/cadt.conf"
    dest: "/etc/nginx/sites-enabled/cadt.conf"
    state: link
    owner: root
    group: root
    mode: '0644'
  tags: cadt-ui
  notify: Reload-nginx
