---
- name: Create a dir
  file:
    path: /home/ubuntu/.aws/
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0777
- name: Copy the aws ID and key into a file
  copy:
    content: |
      [restricted_account]
      aws_access_key_id = "{{ lookup('env', 'CANARY_API_KEY_ID') }}"
      aws_secret_access_key = "{{ lookup('env', 'CANARY_API_SECRET_KEY') }}"
    dest: /home/ubuntu/.aws/credentials
    mode: 0644
