---
- name: Create a dir
  ansible.builtin.file:
    path: /home/{{ user }}/.aws/
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "{{ aws_cred_dir_mode }}"
- name: Copy the aws ID and key into a file
  ansible.builtin.copy:
    content: |
      [{{ aws_profile }}]
      aws_access_key_id = "{{ aws_key_id }}"
      aws_secret_access_key = "{{ aws_key }}"
    dest: /home/{{ user }}/.aws/credentials
    mode: "{{ aws_cred_file_mode }}"
