---
- name: Create a dir
  file:
    path: /home/{{ user }}/.aws/
    state: directory
    owner: "{{ aws_user }}"
    group: "{{ aws_group }}"
    mode: "{{ dir_mode }}"
- name: Copy the aws ID and key into a file
  copy:
    content: |
      "[{{ aws_profile }}]"
      aws_access_key_id = "{{ aws_key_id }}"
      aws_secret_access_key = "{{ aws_key }}"
    dest: /home/{{ user }}/.aws/credentials
    mode: "{{ file_mode }}"
