---
- name: Create Nginx host for datalayer http proxy
  become: true
  ansible.builtin.template:
    src: datalayer.conf.j2
    dest: /etc/nginx/conf.d/{{ datalayer_public_host }}.conf
    owner: root
    group: root
    mode: '0644'
  tags: datalayer-proxy
  notify: Reload-nginx

- name: Create directory for Datalayer proxy includes
  become: true
  ansible.builtin.file:
    path: /etc/nginx/datalayer_proxy_includes
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
  tags: datalayer-proxy

- name: Nginx include file for datalayer HTTP proxy
  become: true
  ansible.builtin.template:
    src: datalayer-proxy.inc.j2
    dest: /etc/nginx/datalayer_proxy_includes/datalayer-proxy-{{ chia_data_layer_host_port }}.inc
    owner: root
    group: root
    mode: '0644'
  tags: datalayer-proxy
  notify: Reload-nginx
