---
- name: Create Nginx host for datalayer http proxy
  become: true
  ansible.builtin.template:
    src: datalayer.conf.j2
    dest: /etc/nginx/conf.d/{{ datalayer_public_host }}.conf
    owner: root
    group: root
    mode: '0644'
  tags: datalayer-proxy
  notify: Reload-nginx

- name: Create directory for Datalayer includes
  become: true
  ansible.builtin.file:
    path: /etc/nginx/datalayer_includes
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"
  tags: datalayer-proxy

- name: Create webroot for datalayer .dat files when direct serve
  become: true
  ansible.builtin.file:
    path: "{{ datalayer_direct_webroot }}"
    state: directory
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"
  tags: datalayer-proxy
  when: datalayer_serving_type == 'direct'

- name: Check if the default Chia datalayer file path is a symlink
  ansible.builtin.stat:
    path: "{{ chia_root }}/data_layer/db/server_files_location_{{ network }}"
  register: mylinks

- name: If datalayer file path exists but is not a symlink, copy all files to the new directory
  ansible.builtin.copy:
    remote_src: true
    src: "{{ chia_root }}/data_layer/db/server_files_location_{{ network }}/"
    dest: "{{ datalayer_direct_webroot }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0644'
  tags: datalayer-proxy
  when: datalayer_serving_type == 'direct' and mylinks.stat.exists and (mylinks.stat.islnk is not defined or mylinks.stat.islnk is false)

- name: If datalayer file path exists but is not a symlink, delete directory
  ansible.builtin.file:
    file: "{{ chia_root }}/data_layer/db/server_files_location_{{ network }}/"
    state: absent
  tags: datalayer-proxy
  when: datalayer_serving_type == 'direct' and mylinks.stat.exists and (mylinks.stat.islnk is not defined or mylinks.stat.islnk is false)

- name: Create symlink to new datalayer file location
  ansible.builtin.file:
    src: "{{ datalayer_direct_webroot }}"
    dest: "{{ chia_root }}/data_layer/db/server_files_location_{{ network }}"
    state: link
    owner: "{{ user }}"
    group: "{{ group }}"
  tags: datalayer-proxy
  when: datalayer_serving_type == 'direct'

- name: Nginx include file for datalayer HTTP proxy or direct file serve
  become: true
  ansible.builtin.template:
    src: datalayer-{{ datalayer_serving_type }}.inc.j2
    dest: /etc/nginx/datalayer_includes/datalayer-{{ datalayer_public_host }}.{{ datalayer_public_path }}.inc
    owner: root
    group: root
    mode: '0644'
  tags: datalayer-proxy
  notify: Reload-nginx
