---
# chia-runner/tasks/main.yml

- name: Insert the proper path for gnu-tar in .zshenv.
  lineinfile:
    path: "~/.zshenv"
    line: export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
    insertbefore: EOF

- name: Make action-runner directory
  ansible.builtin.file:
    path: "{{ path_to_runner_directory }}"
    state: directory
    mode: '0755'

- name: Download runner tarball
  get_url:
    url: https://github.com/actions/runner/releases/download/v{{runner_release_version}}/actions-runner-osx-x64-{{runner_release_version}}.tar.gz
    dest: "{{ path_to_runner_directory }}"
    mode: '0755'

- name: Unarchive runner tarball
  ansible.builtin.unarchive:
    src: "{{ path_to_runner_directory }}/actions-runner-osx-x64-{{runner_release_version}}.tar.gz"
    dest: "{{ path_to_runner_directory }}"
    remote_src: yes
    list_files: yes
    creates: "{{ path_to_runner_directory }}/svc.sh"

- name: Configure the runner for GitHub
  shell: ./config.sh --url https://github.com/Chia-Network --token "{{registration_token}}" --runnergroup "{{runner_group}}" --labels "{{runner_tags}}" --name "{{runner_name}}" --unattended
  args:
    chdir: "{{ path_to_runner_directory }}"
    creates: "{{ path_to_runner_directory }}/svc.sh"

- name: Install the runner service
  shell: |
    arch -x86_64 ./svc.sh install
  args:
    chdir: "{{ path_to_runner_directory }}"
    creates: "{{ path_to_service_file }}"

- name:  Start the runner service
  shell: |
    arch -x86_64 ./svc.sh start
    arch -x86_64 ./svc.sh status
  register: output

- name: Display the output in Ansible
  debug: msg:"{{ output.stdout }}"

