---
# chia-runner/tasks/main.yml
- name: Clone runner code and unzip
  stat:
    path: /Library/LaunchAgents/actions.runner.Chia-Network.m1-01.plist
  register: runner_file
  when: not runner_file.stat.exists
  shell: |
    mkdir actions-runner && cd actions-runner
    curl -O -L https://github.com/actions/runner/releases/download/v"{{ runner_release_version }}"/actions-runner-osx-x64-"{{ runner_release_version }}".tar.gz
    tar xzf ./actions-runner-osx-x64-"{{ runner_release_version }}".tar.gz
    ./config.sh --url https://github.com/Chia-Network --token ATAQBLQ36XEKM6ED6XQ7FNDBHE6ZM --runnergroup "M1 Runners" --labels macOS,self-hosted,X64,m1 --name m1-01 --work _work
  become_user: chia-network

- name: Install the runner service
  become: chia-network
  shell: "{{ path_to_service }}/svc.sh install"


