---
# chia-runner/tasks/main.yml
- name: Clone runner code and unzip
  shell: |
    mkdir actions-runner && cd actions-runner
    curl -O -L https://github.com/actions/runner/releases/download/v"{{ runner_release_version }}"/actions-runner-osx-x64-"{{ runner_release_version }}".tar.gz
    tar xzf ./actions-runner-osx-x64-"{{ runner_release_version }}".tar.gz
  become_user: chia-network

- name: Install the runner service
  become: chia-network
  shell: "{{ path_to_service }}/svc.sh install"


