---
# Some packages being updated via automation cause issues, hold these back
- name: Hold packages
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: "{{ apt_update_hold_items }}"
  register: apt_action
  retries: 100
  until: apt_action is success or ('locked by another process' not in apt_action.msg)
  # This PR https://github.com/ansible/ansible/pull/81406
  # Made this step fail if a package was unknown. We have a list of packages that may not necessarily be on all hosts
  # and we want this to not fail just because a package doesn't exist for a particular host
  failed_when:
    - apt_action.failed
    - '"Failed to find package" not in apt_action.msg'

- name: Ensure apt packages are all up to date
  become: true
  ansible.builtin.apt:
    name: "*"
    update_cache: true
    cache_valid_time: 300
    state: latest
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Unhold packages
  become: true
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  with_items: "{{ apt_update_hold_items }}"
  register: apt_action
  retries: 100
  until: apt_action is success or ('locked by another process' not in apt_action.msg)
  # This PR https://github.com/ansible/ansible/pull/81406
  # Made this step fail if a package was unknown. We have a list of packages that may not necessarily be on all hosts
  # and we want this to not fail just because a package doesn't exist for a particular host
  failed_when:
    - apt_action.failed
    - '"Failed to find package" not in apt_action.msg'
