- name: restart-chia
  become: yes
  service:
    name: "{{ chia_service_base }}-{{ item }}.service"
    state: restarted
  when: start_now
  with_items: "{{ chia_enabled_services }}"

- name: restart-vector
  become: yes
  service:
    name: vector
    state: restarted
  when: add_vector_config and vector_start_now

- name: restart-monit
  become: yes
  service:
    name: monit
    state: restarted
  when: add_monit_config and monit_start_now
