- name: systemd-daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart-chia
  become: true
  ansible.builtin.service:
    name: "{{ chia_service_base }}.target"
    state: restarted
  when: start_now
  register: systemd_action
  retries: 10
  until: systemd_action is success

- name: restart-monit
  become: true
  ansible.builtin.service:
    name: monit
    state: restarted
  when: (add_monit_config or chia_add_hw_vdf_monit_config) and monit_start_now
  register: systemd_action
  retries: 10
  until: systemd_action is success
