- name: restart-chia
  become: yes
  service:
    name: chia
    state: restarted
  when: start_now

- name: restart-vector
  service:
    name: vector
    state: restarted
  when: add_vector_config

- name: restart-monit
  service:
    name: monit
    state: restarted
  when: add_monit_config

