---
# userify/tasks/main.yml
- name: get userify shim
  get_url:
    url: https://shim.userify.com/installer.sh
    dest: /tmp
    mode: 0777
  notify: start_userify

- name: install userify
  shell: './installer.sh'
  args:
    chdir: /tmp
    creates: /opt/userify
  environment:
    api_id: "{{userify_api_id}}"
    api_key: "{{userify_api_key}}"
  notify: start_userify

- name: wrap shim with systemd
  copy:
    src: files/userify
    dest: /etc/systemd/system/userify.service
    owner: root
    group: root
    mode: 0755
  notify: start_userify

# chia-runner/tasks/main.yml
- name: Clone runner code and unzip
  shell: mkdir actions-runner && cd actions-runner && curl -O -L https://github.com/actions/runner/releases/download/v2.273.5/actions-runner-linux-x64-2.273.5.tar.gz && tar xzf ./actions-runner-linux-x64-2.273.5.tar.gz
  become: yes
  become_user: ubuntu

- name: Copy Service File TO AMI
  copy:
    src: files/runner-service
    dest: /etc/systemd/system/github-runner.service
    owner: root
    group: root
    mode: 0755

- name: Extend Packer Max Timeout
  shell: export AWS_POLL_DELAY_SECONDS=60 && export AWS_MAX_ATTEMPTS=180
  become: yes
