---
- name: Add vector key
  become: yes
  ansible.builtin.apt_key:
    url: https://keys.datadoghq.com/DATADOG_APT_KEY_CURRENT.public
    state: present
    keyring: /usr/share/keyrings/datadog-archive-keyring.gpg

- name: Add vector repository
  become: yes
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/datadog-archive-keyring.gpg] https://apt.vector.dev/ stable vector-0
    update_cache: true

- name: Install vector
  become: yes
  ansible.builtin.apt:
    name: vector
    state: present
  notify: restart-vector
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Template vector config
  become: yes
  template:
    src: vector.toml
    dest: /etc/vector/vector.toml

- name: Ensure the example configs are not present
  become: yes
  ansible.builtin.file:
    path: /etc/vector/examples
    state: absent

- name: Template systemd config
  become: yes
  template:
    src: vector.service
    dest: /etc/systemd/system/vector.service

- name: Add the vector user to the ubuntu group so it can read log files owned by ubuntu
  become: yes
  ansible.builtin.user:
    name: vector
    groups: ubuntu
    append: yes

- name: Set desired boot state
  become: yes
  ansible.builtin.systemd:
    name: vector
    daemon_reload: true
    enabled: "{{ vector_start_on_boot }}"

- name: Set desired current state
  become: yes
  ansible.builtin.systemd:
    name: vector
    state: "{{ vector_start_now | ternary('started','stopped') }}"
  ignore_errors: yes # In case we have a bad config and we need to finish the playbook to continue
