---
- name: Add vector key
  ansible.builtin.apt_key:
    url: https://repositories.timber.io/public/vector/gpg.3543DB2D0A2BC4B8.key
    state: present

- name: Add vector repository
  ansible.builtin.template:
    src: timber-vector.list
    dest: /etc/apt/sources.list.d/timber-vector.list

- name: Install vector
  ansible.builtin.apt:
    name: vector
    update_cache: yes
    state: present
  notify: restart-vector

- name: Template vector config
  template:
    src: vector.toml
    dest: /etc/vector/vector.toml

- name: Template systemd config
  template:
    src: vector.service
    dest: /etc/systemd/system/vector.service

- name: Set desired boot state
  ansible.builtin.systemd:
    name: vector
    daemon_reload: true
    enabled: "{{ vector_start_on_boot }}"

- name: Set desired current state
  ansible.builtin.systemd:
    name: vector
    state: "{{ vector_start_now | ternary('started','stopped') }}"
  ignore_errors: yes # In case we have a bad config and we need to finish the playbook to continue
