---
- name: Install Podman
  become: yes
  ansible.builtin.apt:
    name:
      - podman
    update_cache: yes
    cache_valid_time: 300
    register: apt_install
    retries: 100
    until: apt_install is success or ('Failed to lock apt for exclusive operation' not in apt_install.msg and '/var/lib/dpkg/lock' not in apt_install.msg)
