---
# Installing from PIP to ensure this can also work on arm
- name: Install python deps
  become: yes
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    update_cache: yes
    cache_valid_time: 300
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: Install b2 from pip
  become: true
  become_user: "{{ user }}"
  ansible.builtin.pip:
    name: b2
    extra_args: --user

- name: Ensure pip bin directory is in PATH
  become: true
  become_user: "{{ user }}"
  ansible.builtin.lineinfile:
    path: "/home/{{ user }}/.bashrc"
    line: "export PATH=/home/{{ user }}/.local/bin:$PATH"
